import { ShipParameters, ParamConfigGroups, LightParameters, EnvironmentPreset } from './types';
import { STOCK_SHIPS } from './ships';

export const INITIAL_SHIP_PARAMS: ShipParameters = STOCK_SHIPS['Stargazer Class'];

export const INITIAL_LIGHT_PARAMS: LightParameters = {
    directional_enabled: true,
    directional_intensity: 1,
    directional_color: '#ffffff',
    directional_position_x: 10,
    directional_position_y: 20,
    directional_position_z: 5,

    ambient_enabled: true,
    ambient_intensity: 1.0,
    ambient_color: '#ffffff',

    env_enabled: false,
    env_intensity: 1,
    env_preset: 'city',
};

export const ENVIRONMENT_PRESETS: EnvironmentPreset[] = ['city', 'sunset', 'dawn', 'night', 'warehouse', 'forest', 'apartment', 'studio', 'lobby'];

export const LIGHT_PARAM_CONFIG: ParamConfigGroups = {
    "Directional Light": {
        directional_enabled: { label: "Enable", type: 'toggle' },
        directional_intensity: { label: "Intensity", min: 0, max: 5, step: 0.1, type: 'slider' },
        directional_color: { label: "Color", type: 'color' },
        directional_position_x: { label: "Position X", min: -50, max: 50, step: 1, type: 'slider' },
        directional_position_y: { label: "Position Y", min: -50, max: 50, step: 1, type: 'slider' },
        directional_position_z: { label: "Position Z", min: -50, max: 50, step: 1, type: 'slider' },
    },
    "Ambient Light": {
        ambient_enabled: { label: "Enable", type: 'toggle' },
        ambient_intensity: { label: "Intensity", min: 0, max: 2, step: 0.05, type: 'slider' },
        ambient_color: { label: "Color", type: 'color' },
    },
    "Environment": {
        env_enabled: { label: "Enable", type: 'toggle' },
        env_intensity: { label: "Intensity", min: 0, max: 2, step: 0.05, type: 'slider' },
        env_preset: { label: "Preset", type: 'select', options: ENVIRONMENT_PRESETS },
    }
};

export const PARAM_CONFIG: ParamConfigGroups = {
  "Hull Texturing": {
    texture_toggle: { label: "Enable Textures", type: 'toggle' },
    texture_seed: { label: "Seed", min: 0, max: 1000, step: 1, type: 'slider' },
    texture_scale: { label: "Panel Scale", min: 2, max: 20, step: 0.1, type: 'slider' },
    texture_density: { label: "Detail Density", min: 0.1, max: 1.0, step: 0.01, type: 'slider' },
    texture_panel_color_variation: { label: "Panel Color Variation", min: 0, max: 0.2, step: 0.01, type: 'slider' },
    texture_window_color1: { label: "Window Color 1", type: 'color' },
    texture_window_color2: { label: "Window Color 2", type: 'color' },
    texture_window_density: { label: "Window Density", min: 0, max: 1, step: 0.01, type: 'slider' },
    texture_emissive_intensity: { label: "Window Glow", min: 0, max: 5, step: 0.01, type: 'slider' },
  },
  "Primary Hull (Saucer)": {
    primary_toggle: { label: "Enable", type: 'toggle' },
    primary_y: { label: "Fore/Aft Position", min: -40, max: 40, step: 0.01, type: 'slider' },
    primary_z: { label: "Vertical Position", min: -20, max: 20, step: 0.01, type: 'slider' },
    primary_radius: { label: "Radius", min: 1, max: 40, step: 0.01, type: 'slider' },
    primary_thickness: { label: "Thickness", min: 0.5, max: 30, step: 0.01, type: 'slider' },
    primary_widthRatio: { label: "Width Ratio", min: 0.01, max: 3, step: 0.01, type: 'slider' },
    primary_pointiness: { label: "Pointiness", min: -0.95, max: 4, step: 0.01, type: 'slider' },
    primary_notch_fore: { label: "Notch Angle (Fore)", min: -Math.PI / 4, max: Math.PI / 2, step: 0.01, type: 'slider' },
    primary_notch_aft: { label: "Notch Angle (Aft)", min: -Math.PI / 4, max: Math.PI / 2, step: 0.01, type: 'slider' },
    primary_segments: { label: "Segments", min: 8, max: 128, step: 1, type: 'slider' },
  },
  "Bridge": {
    primary_bridgeThickness: { label: "Thickness", min: 0.1, max: 5, step: 0.01, type: 'slider' },
    primary_bridgeRadius: { label: "Radius", min: 0.001, max: 4, step: 0.01, type: 'slider' },
    primary_bridgeWidthRatio: { label: "Width Ratio", min: 0.2, max: 2, step: 0.01, type: 'slider' },
    primary_bridgeY: { label: "Fore/Aft Offset", min: -20, max: 20, step: 0.01, type: 'slider' },
    primary_bridgeZ: { label: "Vertical Offset", min: -10, max: 10, step: 0.01, type: 'slider' },
    primary_bridgeSegments: { label: "Segments", min: 8, max: 64, step: 1, type: 'slider' },
  },
  "Connecting Neck": {
    neck_toggle: { label: "Enable", type: 'toggle' },
    neck_primaryForeOffset: { label: "Saucer Attach (Fore)", min: -0.5, max: 1.5, step: 0.01, type: 'slider' },
    neck_primaryAftOffset: { label: "Saucer Attach (Aft)", min: -0.5, max: 1.5, step: 0.01, type: 'slider' },
    neck_engineeringForeOffset: { label: "Eng. Attach (Fore)", min: -0.5, max: 1.5, step: 0.01, type: 'slider' },
    neck_engineeringAftOffset: { label: "Eng. Attach (Aft)", min: -0.5, max: 1.5, step: 0.01, type: 'slider' },
    neck_primaryThickness: { label: "Width", min: 0.1, max: 5, step: 0.01, type: 'slider' },
    neck_foretaper: { label: "Taper (Fore)", min: 0.1, max: 3, step: 0.01, type: 'slider' },
    neck_afttaper: { label: "Taper (Aft)", min: 0.1, max: 3, step: 0.01, type: 'slider' },
    neck_taperSaucer: { label: "Taper (Saucer)", min: 0.1, max: 3, step: 0.01, type: 'slider' },
    neck_taperEng: { label: "Taper (Eng.)", min: 0.1, max: 3, step: 0.01, type: 'slider' },
    neck_undercut: { label: "Undercut Amount", min: 0, max: 0.95, step: 0.01, type: 'slider' },
    neck_undercut_location: { label: "Undercut Location", min: 0, max: 1, step: 0.01, type: 'slider' },
    neck_undercut_width: { label: "Undercut Width", min: 0.01, max: 1, step: 0.01, type: 'slider' },
    neck_undercut_curve: { label: "Undercut Curve", min: 0.1, max: 8, step: 0.01, type: 'slider' },
  },
  "Engineering Hull": {
    engineering_toggle: { label: "Enable", type: 'toggle' },
    engineering_y: { label: "Fore/Aft Position", min: -50, max: 30, step: 0.01, type: 'slider' },
    engineering_z: { label: "Vertical Position", min: -10, max: 11, step: 0.01, type: 'slider' },
    engineering_length: { label: "Length", min: 5, max: 30, step: 0.01, type: 'slider' },
    engineering_radius: { label: "Radius", min: 0.5, max: 5, step: 0.01, type: 'slider' },
    engineering_widthRatio: { label: "Width Ratio", min: 0.5, max: 8, step: 0.01, type: 'slider' },
    engineering_dishType: { label: 'Deflector Style', type: 'select', options: ['Pulse', 'Movie Refit', 'Vortex', 'TNG'] },
    engineering_dishRadius: { label: "Deflector Radius", min: 0, max: 1.5, step: 0.01, type: 'slider' },
    engineering_dishInset: { label: "Deflector Inset", min: -2, max: 5, step: 0.01, type: 'slider' },
    engineering_dishColor1: { label: 'Deflector Color A', type: 'color' },
    engineering_dishColor2: { label: 'Deflector Color B', type: 'color' },
    engineering_dishColor3: { label: 'Deflector Color C', type: 'color' },
    engineering_dishColor4: { label: 'Deflector Color D', type: 'color' },
    engineering_dishGlowIntensity: { label: 'Deflector Glow', min: 0, max: 10, step: 0.1, type: 'slider' },
    engineering_dishAnimSpeed: { label: 'Deflector Pulse', min: 0, max: 5, step: 0.1, type: 'slider' },
    engineering_dishTextureScaleX: { label: 'Deflector Texture Scale X', min: 0.1, max: 5, step: 0.01, type: 'slider' },
    engineering_dishTextureScaleY: { label: 'Deflector Texture Scale Y', min: 0.1, max: 5, step: 0.01, type: 'slider' },
    engineering_dishTextureShearX: { label: 'Deflector Texture Shear X', min: -2, max: 2, step: 0.01, type: 'slider' },
    engineering_dishTextureShearY: { label: 'Deflector Texture Shear Y', min: -2, max: 2, step: 0.01, type: 'slider' },
    engineering_skew: { label: "Skew", min: -5, max: 5, step: 0.01, type: 'slider' },
    engineering_undercut: { label: "Undercut (Bottom)", min: 0, max: 1, step: 0.01, type: 'slider' },
    engineering_undercutStart: { label: "Undercut Start (Bottom)", min: 0, max: 1, step: 0.01, type: 'slider' },
    engineering_undercutCurve: { label: "Undercut Curve (Bottom)", min: 0.1, max: 8, step: 0.01, type: 'slider' },
    engineering_topcut: { label: "Undercut (Top)", min: 0, max: 1, step: 0.01, type: 'slider' },
    engineering_topcutStart: { label: "Undercut Start (Top)", min: 0, max: 1, step: 0.01, type: 'slider' },
    engineering_topcutCurve: { label: "Undercut Curve (Top)", min: 0.1, max: 8, step: 0.01, type: 'slider' },
    engineering_segments: { label: "Segments", min: 8, max: 64, step: 1, type: 'slider' },
  },
   "Impulse Engines": {
    sublight_toggle: { label: "Enable", type: 'toggle' },
    sublight_color1: { label: 'Base Color', type: 'color' },
    sublight_color2: { label: 'Glow Color', type: 'color' },
    sublight_glowIntensity: { label: 'Glow Intensity', min: 0, max: 10, step: 0.1, type: 'slider' },
    sublight_animSpeed: { label: 'Pulse Speed', min: 0, max: 5, step: 0.1, type: 'slider' },
    sublight_y: { label: "Fore/Aft Position", min: -40, max: 40, step: 0.01, type: 'slider' },
    sublight_x: { label: "X Spread", min: 0, max: 10, step: 0.01, type: 'slider' },
    sublight_z: { label: "Vertical Position", min: -20, max: 20, step: 0.01, type: 'slider' },
    sublight_length: { label: "Length", min: 1, max: 10, step: 0.01, type: 'slider' },
    sublight_radius: { label: "Radius", min: 0.1, max: 5, step: 0.01, type: 'slider' },
    sublight_widthRatio: { label: "Width Ratio", min: 0.2, max: 5, step: 0.01, type: 'slider' },
    sublight_rotation: { label: "Rotation", min: -Math.PI, max: Math.PI, step: 0.01, type: 'slider' },
    sublight_skewHorizontal: { label: "Horiz. Skew", min: -1, max: 1, step: 0.01, type: 'slider' },
    sublight_skewVertical: { label: "Vert. Skew", min: -1, max: 1, step: 0.01, type: 'slider' },
    sublight_segments: { label: "Segments", min: 3, max: 32, step: 1, type: 'slider' },
    sublight_wallThickness: { label: "Wall Thickness", min: 0.01, max: 0.9, step: 0.01, type: 'slider' },
    sublight_grillInset: { label: "Grill Inset", min: -1, max: 1, step: 0.01, type: 'slider' },
  },
  "Nacelle Body (Upper)": {
    nacelle_toggle: { label: "Enable", type: 'toggle' },
    nacelle_y: { label: "Fore/Aft Position", min: -20, max: 40, step: 0.01, type: 'slider' },
    nacelle_x: { label: "X Spread", min: 2, max: 20, step: 0.01, type: 'slider' },
    nacelle_z: { label: "Vertical Position", min: -15, max: 15, step: 0.01, type: 'slider' },
    nacelle_length: { label: "Length", min: 5, max: 50, step: 0.01, type: 'slider' },
    nacelle_radius: { label: "Radius", min: 0.5, max: 4, step: 0.01, type: 'slider' },
    nacelle_widthRatio: { label: "Width Ratio", min: 0.5, max: 2, step: 0.01, type: 'slider' },
    nacelle_foreTaper: { label: "Taper (Aft)", min: 0.1, max: 3, step: 0.01, type: 'slider' },
    nacelle_aftTaper: { label: "Taper (Fore)", min: 0.1, max: 3, step: 0.01, type: 'slider' },
    nacelle_rotation: { label: "Rotation", min: -Math.PI / 2, max: Math.PI / 2, step: 0.01, type: 'slider' },
    nacelle_skew: { label: "Skew", min: -5, max: 5, step: 0.01, type: 'slider' },
    nacelle_undercut: { label: "Undercut", min: 0, max: 1, step: 0.01, type: 'slider' },
    nacelle_undercutStart: { label: "Undercut Start", min: 0, max: 1, step: 0.01, type: 'slider' },
    nacelle_segments: { label: "Segments", min: 8, max: 64, step: 1, type: 'slider' },
  },
  "Bussard Collectors (Upper)": {
    nacelle_bussardType: { label: 'Style', type: 'select', options: ['TOS', 'TNG', 'Radiator', 'TNG Swirl'] },
    nacelle_bussardSubtleVanes: { label: 'Subtle Streaks (TNG Swirl)', type: 'toggle' },
    nacelle_bussardVaneCount: { label: 'Vane Count (TOS)', min: 2, max: 15, step: 1, type: 'slider' },
    nacelle_bussardVaneLength: { label: 'Vane Length (TOS)', min: 0.1, max: 2, step: 0.01, type: 'slider' },
    nacelle_bussardColor1: { label: 'Glass Tint (TOS) / Base (TNG/Rad)', type: 'color'},
    nacelle_bussardColor2: { label: 'Glow Color (TOS Core/TNG/Swirl Edge)', type: 'color'},
    nacelle_bussardColor3: { label: 'Glow Color (TOS Edge/Swirl Core)', type: 'color'},
    nacelle_bussardGlowIntensity: { label: 'Glow Intensity', min: 0, max: 10, step: 0.1, type: 'slider'},
    nacelle_bussardShellOpacity: { label: 'Glass Opacity (TOS/Swirl)', min: 0, max: 1, step: 0.01, type: 'slider' },
    nacelle_bussardAnimSpeed: { label: 'Animation Speed', min: -1, max: 1, step: 0.01, type: 'slider'},
    nacelle_bussardRadius: { label: "Radius Scale", min: 0.5, max: 2, step: 0.01, type: 'slider' },
    nacelle_bussardWidthRatio: { label: "Width Ratio", min: 0.5, max: 3, step: 0.01, type: 'slider' },
    nacelle_bussardCurvature: { label: "Curvature", min: 0.25, max: 3, step: 0.01, type: 'slider' },
    nacelle_bussardYOffset: { label: "Fore/Aft Offset", min: -2, max: 2, step: 0.01, type: 'slider' },
    nacelle_bussardZOffset: { label: "Vertical Offset", min: -2, max: 2, step: 0.01, type: 'slider' },
    nacelle_bussardSkewVertical: { label: "Vertical Skew", min: -Math.PI / 4, max: Math.PI/4, step: 0.01, type: 'slider' },
  },
  "Warp Grills (Upper)": {
    nacelle_grill_toggle: { label: "Enable", type: 'toggle' },
    nacelle_grill_length: { label: "Length", min: 0, max: 2, step: 0.01, type: 'slider' },
    nacelle_grill_width: { label: "Width", min: 0, max: 1, step: 0.01, type: 'slider' },
    nacelle_grill_vertical_offset: { label: "Vertical Offset", min: -10, max: 10, step: 0.1, type: 'slider' },
    nacelle_grill_rotation: { label: "Rotation", min: -Math.PI, max: Math.PI, step: 0.01, type: 'slider' },
    nacelle_grill_anim_type: { label: 'Animation', type: 'select', options: ['Flow', 'Pulse', 'Plasma Balls'] },
    nacelle_grill_color1: { label: 'Glow Color 1', type: 'color' },
    nacelle_grill_color2: { label: 'Glow Color 2', type: 'color' },
    nacelle_grill_color3: { label: 'Base Color', type: 'color' },
    nacelle_grill_intensity: { label: 'Glow Intensity', min: 0, max: 10, step: 0.1, type: 'slider' },
    nacelle_grill_animSpeed: { label: 'Animation Speed', min: -5, max: 5, step: 0.1, type: 'slider' },
  },
  "Pylons (Upper)": {
    pylon_toggle: { label: "Enable", type: 'toggle' },
    pylon_nacelleForeOffset: { label: "Nacelle Attach (Fore)", min: -0.5, max: 1.5, step: 0.01, type: 'slider' },
    pylon_nacelleAftOffset: { label: "Nacelle Attach (Aft)", min: -0.5, max: 1.5, step: 0.01, type: 'slider' },
    pylon_engineeringForeOffset: { label: "Eng. Attach (Fore)", min: -0.5, max: 1.5, step: 0.01, type: 'slider' },
    pylon_engineeringAftOffset: { label: "Eng. Attach (Aft)", min: -0.5, max: 1.5, step: 0.01, type: 'slider' },
    pylon_baseSpread: { label: "Base Spread", min: 0, max: 1.5, step: 0.01, type: 'slider' },
    pylon_engineeringZOffset: { label: "Eng. Vertical Offset", min: -5, max: 5, step: 0.01, type: 'slider' },
    pylon_midPointOffset: { label: "Elbow Position", min: 0.01, max: 0.99, step: 0.01, type: 'slider' },
    pylon_midPointOffsetX: { label: "Elbow Offset X (Out/In)", min: -20, max: 20, step: 0.1, type: 'slider' },
    pylon_midPointOffsetY: { label: "Elbow Offset Y (Up/Down)", min: -20, max: 20, step: 0.1, type: 'slider' },
    pylon_midPointOffsetZ: { label: "Elbow Offset Z (Fwd/Aft)", min: -20, max: 20, step: 0.1, type: 'slider' },
    pylon_thickness: { label: "Thickness", min: 0.1, max: 2, step: 0.01, type: 'slider' },
    pylon_subdivisions: { label: "Subdivisions", min: 0, max: 3, step: 1, type: 'slider' },
  },
  "Nacelle Body (Lower)": {
    nacelleLower_toggle: { label: "Enable", type: 'toggle' },
    nacelleLower_y: { label: "Fore/Aft Position", min: -30, max: 30, step: 0.01, type: 'slider' },
    nacelleLower_x: { label: "X Spread", min: 2, max: 15, step: 0.01, type: 'slider' },
    nacelleLower_z: { label: "Vertical Position", min: -10, max: 10, step: 0.01, type: 'slider' },
    nacelleLower_length: { label: "Length", min: 5, max: 50, step: 0.01, type: 'slider' },
    nacelleLower_radius: { label: "Radius", min: 0.5, max: 4, step: 0.01, type: 'slider' },
    nacelleLower_widthRatio: { label: "Width Ratio", min: 0.5, max: 2, step: 0.01, type: 'slider' },
    nacelleLower_foreTaper: { label: "Taper (Aft)", min: 0.1, max: 3, step: 0.01, type: 'slider' },
    nacelleLower_aftTaper: { label: "Taper (Fore)", min: 0.1, max: 3, step: 0.01, type: 'slider' },
    nacelleLower_rotation: { label: "Rotation", min: -Math.PI / 2, max: Math.PI / 2, step: 0.01, type: 'slider' },
    nacelleLower_skew: { label: "Skew", min: -5, max: 5, step: 0.01, type: 'slider' },
    nacelleLower_undercut: { label: "Undercut", min: 0, max: 1, step: 0.01, type: 'slider' },
    nacelleLower_undercutStart: { label: "Undercut Start", min: 0, max: 1, step: 0.01, type: 'slider' },
    nacelleLower_segments: { label: "Segments", min: 8, max: 64, step: 1, type: 'slider' },
  },
  "Bussard Collectors (Lower)": {
    nacelleLower_bussardType: { label: 'Style', type: 'select', options: ['TOS', 'TNG', 'Radiator', 'TNG Swirl'] },
    nacelleLower_bussardSubtleVanes: { label: 'Subtle Streaks (TNG Swirl)', type: 'toggle' },
    nacelleLower_bussardVaneCount: { label: 'Vane Count (TOS)', min: 2, max: 15, step: 1, type: 'slider' },
    nacelleLower_bussardVaneLength: { label: 'Vane Length (TOS)', min: 0.1, max: 2, step: 0.01, type: 'slider' },
    nacelleLower_bussardColor1: { label: 'Glass Tint (TOS) / Base (TNG/Rad)', type: 'color'},
    nacelleLower_bussardColor2: { label: 'Glow Color (TOS Core/TNG/Swirl Edge)', type: 'color'},
    nacelleLower_bussardColor3: { label: 'Glow Color (TOS Edge/Swirl Core)', type: 'color'},
    nacelleLower_bussardGlowIntensity: { label: 'Glow Intensity', min: 0, max: 10, step: 0.1, type: 'slider'},
    nacelleLower_bussardShellOpacity: { label: 'Glass Opacity (TOS/Swirl)', min: 0, max: 1, step: 0.01, type: 'slider' },
    nacelleLower_bussardAnimSpeed: { label: 'Animation Speed', min: -1, max: 1, step: 0.01, type: 'slider'},
    nacelleLower_bussardRadius: { label: "Radius Scale", min: 0.5, max: 2, step: 0.01, type: 'slider' },
    nacelleLower_bussardWidthRatio: { label: "Width Ratio", min: 0.5, max: 6, step: 0.01, type: 'slider' },
    nacelleLower_bussardCurvature: { label: "Curvature", min: 0.25, max: 6, step: 0.01, type: 'slider' },
    nacelleLower_bussardYOffset: { label: "Fore/Aft Offset", min: -2, max: 2, step: 0.01, type: 'slider' },
    nacelleLower_bussardZOffset: { label: "Vertical Offset", min: -2, max: 2, step: 0.01, type: 'slider' },
    nacelleLower_bussardSkewVertical: { label: "Vertical Skew", min: -Math.PI / 4, max: Math.PI/4, step: 0.01, type: 'slider' },
  },
  "Warp Grills (Lower)": {
    nacelleLower_grill_toggle: { label: "Enable", type: 'toggle' },
    nacelleLower_grill_length: { label: "Length", min: 0, max: 2, step: 0.01, type: 'slider' },
    nacelleLower_grill_width: { label: "Width", min: 0, max: 1, step: 0.01, type: 'slider' },
    nacelleLower_grill_vertical_offset: { label: "Vertical Offset", min: -10, max: 10, step: 0.1, type: 'slider' },
    nacelleLower_grill_rotation: { label: "Rotation", min: -Math.PI, max: Math.PI, step: 0.01, type: 'slider' },
    nacelleLower_grill_anim_type: { label: 'Animation', type: 'select', options: ['Flow', 'Pulse', 'Plasma Balls'] },
    nacelleLower_grill_color1: { label: 'Glow Color 1', type: 'color' },
    nacelleLower_grill_color2: { label: 'Glow Color 2', type: 'color' },
    nacelleLower_grill_color3: { label: 'Base Color', type: 'color' },
    nacelleLower_grill_intensity: { label: 'Glow Intensity', min: 0, max: 10, step: 0.1, type: 'slider' },
    nacelleLower_grill_animSpeed: { label: 'Animation Speed', min: -5, max: 5, step: 0.1, type: 'slider' },
  },
  "Lower Boom": {
    boomLower_toggle: { label: "Enable Boom", type: 'toggle' },
  },
  "Pylons (Lower)": {
    pylonLower_toggle: { label: "Enable Pylons", type: 'toggle' },
    pylonLower_nacelleForeOffset: { label: "Nacelle Attach (Fore)", min: -0.5, max: 1.5, step: 0.01, type: 'slider' },
    pylonLower_nacelleAftOffset: { label: "Nacelle Attach (Aft)", min: -0.5, max: 1.5, step: 0.01, type: 'slider' },
    pylonLower_engineeringForeOffset: { label: "Boom Attach (Fore)", min: -0.5, max: 1.5, step: 0.01, type: 'slider' },
    pylonLower_engineeringAftOffset: { label: "Boom Attach (Aft)", min: -0.5, max: 1.5, step: 0.01, type: 'slider' },
    pylonLower_baseSpread: { label: "Base Spread", min: 0, max: 10, step: 0.1, type: 'slider' },
    pylonLower_engineeringZOffset: { label: "Boom Height", min: -5, max: 0, step: 0.01, type: 'slider' },
    pylonLower_midPointOffset: { label: "Elbow Position", min: 0.01, max: 0.99, step: 0.01, type: 'slider' },
    pylonLower_midPointOffsetX: { label: "Elbow Offset X (Out/In)", min: -20, max: 20, step: 0.1, type: 'slider' },
    pylonLower_midPointOffsetY: { label: "Elbow Offset Y (Up/Down)", min: -20, max: 20, step: 0.1, type: 'slider' },
    pylonLower_midPointOffsetZ: { label: "Elbow Offset Z (Fwd/Aft)", min: -20, max: 20, step: 0.1, type: 'slider' },
    pylonLower_thickness: { label: "Thickness", min: 0.1, max: 2, step: 0.01, type: 'slider' },
    pylonLower_subdivisions: { label: "Subdivisions", min: 0, max: 3, step: 1, type: 'slider' },
  }
};